### ISSUE TITLE
XmlException handling

### ISSUE THREAD

**Issue by ciroraggio** [buildingSMART/IDS-Audit-tool#9]
When there is a syntax error in the xml (e.g. '/' missing), it is not written to the logger, but an exception is raised and validation is aborted. Maybe it would be better to report it like the other errors, otherwise the exception must be handled separately.

**Comment by CBenghi** [comment]
Hello @ciroraggio,
thanks for noticing this.

I've added a new test case to the project with an XML structural error like `</ids:name />`  and I've modified the code to catch the exception and notify it. 

Have a look at the `idsTool.tests.IssueTests.Issue09_XmlStructure` test case in the code. 
Feel free to attach here other failing IDS files that you would like to be managed seamlessly, otherwise close the issue, please.

**Comment by ciroraggio** [comment]
Hello @CBenghi, thank you for the update!
